### ISSUE TITLE
Anyway to mimic the 'javadoc.failOnError=false' functionality for this plugin?

### ISSUE THREAD

**Issue by cdancy** [nebula-plugins/gradle-aggregate-javadocs-plugin#4]
I've got a multi-module build and would like to set the javadoc.failOnError=false flag but can't seem to make it work. I've tried overriding all tasks of type Javadoc, both at the global level and for 'allprojects', and still can't seem to make it stick. Any ideas?

**Comment by bmuschko** [comment]
You'd need to set it for the task `aggregateJavadocs`. Alternatively, use `tasks.withType(Javadoc)`.

**Comment by cdancy** [comment]
I've tried this:
`allprojects {
	tasks.withType(Javadoc) {
		failOnError false 
	}
}
`
and while it succeeds nothing is found under 'build/docs/javadoc'. Each projects docs are created but it seems they are not being aggregated for whatever reason.

Attempting to set it for aggregateJavadocs fails saying 'no property javadocs exists for task'.

**Comment by bmuschko** [comment]
You will probably have to wrap your logic into `afterEvaluate`. The task isn't created before [all subprojects are evaluated](https://github.com/nebula-plugins/gradle-aggregate-javadocs-plugin/blob/gradle-2.2/src/main/groovy/nebula/plugin/javadoc/NebulaAggregateJavadocPlugin.groovy#L15).

**Comment by nadavc** [comment]
@cdancy were you able to resolve this?

**Comment by cdancy** [comment]
Yes. Feel free to close. My apologies for not saying something months ago.
