### ISSUE TITLE
Task is ignoring javadoc encoding option

### ISSUE THREAD

**Issue by altavir** [nebula-plugins/gradle-aggregate-javadocs-plugin#6]
I'm writing my documentation in UTF-8 I have corresponding options for all subprojects:
```
javadoc{
    options {
        failOnError = false
        encoding "UTF-8"    
        docEncoding "UTF-8" 
        charSet "UTF-8" 
        linkSource true
    }
} 
```
The default `javadoc` task finishes successfully for all subprojects, but when I am trying to run `aggregateJavadoc`, I get a lot of `error: unmappable character for encoding Cp1252` errors (Cp1252 is a system default). I tried to move javadoc options to root project instead of defining it for each of subprojects, but it does not help.

**Comment by bmuschko** [comment]
You are setting the options for the wrong task. It should be `aggregateJavadoc`.
