### ISSUE TITLE
Working example please

### ISSUE THREAD

**Issue by robmcfeely** [nebula-plugins/gradle-aggregate-javadocs-plugin#7]
This is a great idea but I just cannot get this to work.  I don't see the output dir.  
 Can you contribute a working example?  Do I / Can I put it in the allproject{}  section of the main gradle file?  Do I run with javadoc task?

Please help 

Ive also found others who could do woth some help here too  
http://stackoverflow.com/questions/31454623/aggregate-javadoc-for-android-project-with-multiple-library-modules

**Comment by nadavc** [comment]
Please see https://github.com/nadavc/gradle-aggregate-javadocs-plugin-example for an example. You could also browse the tests in `https://github.com/nebula-plugins/gradle-aggregate-javadocs-plugin/tree/master/src/test/groovy/nebula/plugin/javadoc` for more.
